apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
  labels:
    app: node-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
        owner: darko
        env: dev
    spec:
      containers:
        - name: node-app
          image: darkovski/node-app:1.0
          ports:
            - containerPort: 8080
