apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.environment}}-{{.Release.Name}}-deployment
  labels:
    app: {{.Values.environment}}-{{.Release.Name}}
spec:
  replicas: {{.Values.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{.Values.environment}}-{{.Release.Name}}
  template:
    metadata:
      labels:
        app: {{.Values.environment}}-{{.Release.Name}}
        owner: {{.Values.owner | default "unknown" }}
        env: {{.Values.environment}}
    spec:
      containers:
        - name: node-app
          image: hello-world
          ports:
            - containerPort: 80
