apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: {{.Values.environment}}-{{.Release.Name}}-ingress
spec:
    ingressClassName: nginx
    rules:
    - host: guestbook.initgroup.mk
      http:
        paths:
        - pathType: Prefix
          path: /
          backend:
            serviceName: {{.Values.environment}}-{{.Release.Name}}-svc
            servicePort: 8080